version: 0.0
os: linux
files:
  - source: /
    destination: /opt/www/mnutserver
hooks:
  BeforeInstall:
    - location: scripts/start_server
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/AfterInstall.sh
      runas: deploy
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root

